"""Seed obd2.db with the dtc_codes schema and initial DTC data.

Running this script is idempotent — safe to run multiple times.

Usage:
    uv run seed.py              # writes to ./obd2.db
    uv run seed.py --db /tmp/x  # writes to /tmp/x
"""

import argparse
import sqlite3
from pathlib import Path

DEFAULT_DB_PATH = Path(__file__).parent / "obd2.db"

SCHEMA = """
CREATE TABLE IF NOT EXISTS dtc_codes (
    code        TEXT PRIMARY KEY,
    category    TEXT NOT NULL,
    severity    TEXT NOT NULL DEFAULT 'Warning'
                    CHECK(severity IN ('Critical', 'Warning', 'Info')),
    description TEXT NOT NULL,
    symptoms    TEXT NOT NULL,
    fix         TEXT NOT NULL
);
CREATE VIRTUAL TABLE IF NOT EXISTS dtc_codes_fts USING fts5(
    code,
    category,
    severity,
    description,
    symptoms,
    fix,
    content='dtc_codes',
    content_rowid='rowid'
);
"""

# Trigger to keep FTS index in sync with the main table
FTS_TRIGGERS = """
CREATE TRIGGER IF NOT EXISTS dtc_codes_ai AFTER INSERT ON dtc_codes BEGIN
    INSERT INTO dtc_codes_fts(rowid, code, category, severity, description, symptoms, fix)
    VALUES (new.rowid, new.code, new.category, new.severity, new.description, new.symptoms, new.fix);
END;
CREATE TRIGGER IF NOT EXISTS dtc_codes_ad AFTER DELETE ON dtc_codes BEGIN
    INSERT INTO dtc_codes_fts(dtc_codes_fts, rowid, code, category, severity, description, symptoms, fix)
    VALUES ('delete', old.rowid, old.code, old.category, old.severity, old.description, old.symptoms, old.fix);
END;
CREATE TRIGGER IF NOT EXISTS dtc_codes_au AFTER UPDATE ON dtc_codes BEGIN
    INSERT INTO dtc_codes_fts(dtc_codes_fts, rowid, code, category, severity, description, symptoms, fix)
    VALUES ('delete', old.rowid, old.code, old.category, old.severity, old.description, old.symptoms, old.fix);
    INSERT INTO dtc_codes_fts(rowid, code, category, severity, description, symptoms, fix)
    VALUES (new.rowid, new.code, new.category, new.severity, new.description, new.symptoms, new.fix);
END;
"""

# (code, category, description, symptoms, fix)
DTC_DATA: list[tuple[str, str, str, str, str, str]] = [
    # ── Fuel & Air ─────────────────────────────────────────────────────────────
    (
        "P0100",
        "Fuel & Air",
        "Warning",
        "Mass Air Flow (MAF) Sensor Circuit Malfunction",
        "Poor acceleration, rough idle, stalling, black smoke from exhaust",
        "Inspect MAF sensor wiring harness and connectors; clean or replace MAF sensor",
    ),
    (
        "P0101",
        "Fuel & Air",
        "Warning",
        "Mass Air Flow (MAF) Sensor Circuit Range/Performance",
        "Hesitation during acceleration, poor fuel economy, rough idle",
        "Clean MAF sensor with MAF-safe cleaner; check for air leaks between MAF and throttle body; replace MAF sensor if fault persists",
    ),
    (
        "P0102",
        "Fuel & Air",
        "Warning",
        "Mass Air Flow (MAF) Sensor Circuit Low Input",
        "Hard starting, stalling, black smoke, check engine light",
        "Inspect MAF wiring for short to ground; replace MAF sensor",
    ),
    (
        "P0103",
        "Fuel & Air",
        "Warning",
        "Mass Air Flow (MAF) Sensor Circuit High Input",
        "Stalling, poor power, check engine light",
        "Inspect MAF sensor wiring for open circuit; replace MAF sensor",
    ),
    (
        "P0110",
        "Fuel & Air",
        "Info",
        "Intake Air Temperature (IAT) Sensor Circuit Malfunction",
        "Poor fuel economy, rough idle, difficulty starting in cold weather",
        "Inspect IAT sensor wiring; replace IAT sensor or MAF/IAT combined sensor",
    ),
    (
        "P0128",
        "Cooling",
        "Info",
        "Coolant Temperature Below Thermostat Regulating Temperature",
        "Heater performs poorly, temperature gauge stays low, poor fuel economy",
        "Replace the engine thermostat; inspect coolant temperature sensor",
    ),
    (
        "P0171",
        "Fuel & Air",
        "Warning",
        "System Too Lean (Bank 1)",
        "Rough idle, hesitation, check engine light, poor fuel economy, misfires",
        "Check for vacuum leaks, inspect MAF sensor, test fuel pressure and injectors, replace oxygen sensor if faulty",
    ),
    (
        "P0172",
        "Fuel & Air",
        "Warning",
        "System Too Rich (Bank 1)",
        "Black smoke from exhaust, poor fuel economy, rough idle, fuel smell",
        "Inspect MAF sensor for contamination, check for leaking fuel injectors, test fuel pressure regulator",
    ),
    (
        "P0173",
        "Fuel & Air",
        "Warning",
        "Fuel Trim Malfunction (Bank 2)",
        "Poor fuel economy, rough idle, check engine light",
        "Inspect vacuum lines and intake manifold gasket on Bank 2; test MAF sensor",
    ),
    (
        "P0174",
        "Fuel & Air",
        "Warning",
        "System Too Lean (Bank 2)",
        "Rough idle, hesitation, check engine light, poor fuel economy (Bank 2 side)",
        "Check for vacuum leaks on Bank 2 side, inspect MAF sensor, test fuel pressure",
    ),
    (
        "P0175",
        "Fuel & Air",
        "Warning",
        "System Too Rich (Bank 2)",
        "Black smoke from exhaust (Bank 2), poor fuel economy, rough idle",
        "Inspect fuel injectors on Bank 2 for leaks; test fuel pressure; clean MAF sensor",
    ),
    (
        "P0190",
        "Fuel & Air",
        "Warning",
        "Fuel Rail Pressure Sensor Circuit Malfunction",
        "Hard starting, stalling, poor performance, check engine light",
        "Inspect fuel rail pressure sensor wiring; test and replace sensor; check fuel pump output",
    ),
    (
        "P0191",
        "Fuel & Air",
        "Warning",
        "Fuel Rail Pressure Sensor Circuit Range/Performance",
        "Hesitation, stalling, poor fuel economy",
        "Test fuel pump pressure; inspect fuel pressure regulator; check sensor wiring",
    ),
    # ── Ignition / Misfire ──────────────────────────────────────────────────────
    (
        "P0300",
        "Ignition",
        "Warning",
        "Random/Multiple Cylinder Misfire Detected",
        "Rough idle, shaking, flashing check engine light, loss of power",
        "Inspect and replace spark plugs, ignition coils, or fuel injectors; check compression; inspect for vacuum leaks",
    ),
    (
        "P0301",
        "Ignition",
        "Warning",
        "Cylinder 1 Misfire Detected",
        "Rough idle, shaking, loss of power, check engine light flashing",
        "Replace spark plug and ignition coil on cylinder 1; inspect fuel injector; check compression on cylinder 1",
    ),
    (
        "P0302",
        "Ignition",
        "Warning",
        "Cylinder 2 Misfire Detected",
        "Rough idle, shaking, loss of power, check engine light flashing",
        "Replace spark plug and ignition coil on cylinder 2; inspect fuel injector; check compression on cylinder 2",
    ),
    (
        "P0303",
        "Ignition",
        "Warning",
        "Cylinder 3 Misfire Detected",
        "Rough idle, shaking, loss of power, check engine light flashing",
        "Replace spark plug and ignition coil on cylinder 3; inspect fuel injector; check compression on cylinder 3",
    ),
    (
        "P0304",
        "Ignition",
        "Warning",
        "Cylinder 4 Misfire Detected",
        "Rough idle, shaking, loss of power, check engine light flashing",
        "Replace spark plug and ignition coil on cylinder 4; inspect fuel injector; check compression on cylinder 4",
    ),
    (
        "P0305",
        "Ignition",
        "Warning",
        "Cylinder 5 Misfire Detected",
        "Rough idle, shaking, loss of power, check engine light flashing",
        "Replace spark plug and ignition coil on cylinder 5; inspect fuel injector; check compression on cylinder 5",
    ),
    (
        "P0306",
        "Ignition",
        "Warning",
        "Cylinder 6 Misfire Detected",
        "Rough idle, shaking, loss of power, check engine light flashing",
        "Replace spark plug and ignition coil on cylinder 6; inspect fuel injector; check compression on cylinder 6",
    ),
    (
        "P0316",
        "Ignition",
        "Warning",
        "Misfire Detected On Startup (First 1000 Revolutions)",
        "Rough start, shaking on cold start, check engine light",
        "Inspect spark plugs and coils; check for fuel delivery issues; inspect PCV system",
    ),
    (
        "P0351",
        "Ignition",
        "Warning",
        "Ignition Coil A Primary/Secondary Circuit Malfunction",
        "Misfire on cylinder 1, rough idle, check engine light",
        "Test and replace ignition coil A; inspect wiring harness to coil A",
    ),
    (
        "P0352",
        "Ignition",
        "Warning",
        "Ignition Coil B Primary/Secondary Circuit Malfunction",
        "Misfire on cylinder 2, rough idle, check engine light",
        "Test and replace ignition coil B; inspect wiring harness to coil B",
    ),
    # ── Oxygen Sensors ──────────────────────────────────────────────────────────
    (
        "P0130",
        "Oxygen Sensors",
        "Warning",
        "O2 Sensor Circuit Malfunction (Bank 1, Sensor 1)",
        "Poor fuel economy, rough running, failed emissions test",
        "Inspect upstream O2 sensor wiring on Bank 1; replace sensor",
    ),
    (
        "P0131",
        "Oxygen Sensors",
        "Warning",
        "O2 Sensor Circuit Low Voltage (Bank 1, Sensor 1)",
        "Poor fuel economy, rough running, failed emissions test",
        "Inspect O2 sensor wiring for damage; replace upstream O2 sensor on Bank 1",
    ),
    (
        "P0132",
        "Oxygen Sensors",
        "Warning",
        "O2 Sensor Circuit High Voltage (Bank 1, Sensor 1)",
        "Rich running condition, poor fuel economy, failed emissions test",
        "Check for stuck-rich condition (leaking injectors); replace upstream O2 sensor if wiring is intact",
    ),
    (
        "P0133",
        "Oxygen Sensors",
        "Warning",
        "O2 Sensor Circuit Slow Response (Bank 1, Sensor 1)",
        "Poor fuel economy, failed emissions test",
        "Replace upstream O2 sensor on Bank 1; check for exhaust leaks before sensor",
    ),
    (
        "P0136",
        "Oxygen Sensors",
        "Warning",
        "O2 Sensor Circuit Malfunction (Bank 1, Sensor 2)",
        "Check engine light, potential poor fuel economy",
        "Inspect downstream O2 sensor wiring on Bank 1; replace sensor",
    ),
    (
        "P0141",
        "Oxygen Sensors",
        "Warning",
        "O2 Sensor Heater Circuit Malfunction (Bank 1, Sensor 2)",
        "Poor fuel economy, check engine light, failed emissions test",
        "Replace downstream (post-cat) O2 sensor on Bank 1; check fuse and wiring for sensor heater circuit",
    ),
    (
        "P0150",
        "Oxygen Sensors",
        "Warning",
        "O2 Sensor Circuit Malfunction (Bank 2, Sensor 1)",
        "Poor fuel economy, rough running, failed emissions test (Bank 2)",
        "Inspect upstream O2 sensor wiring on Bank 2; replace sensor",
    ),
    (
        "P0161",
        "Oxygen Sensors",
        "Warning",
        "O2 Sensor Heater Circuit Malfunction (Bank 2, Sensor 2)",
        "Check engine light, failed emissions test",
        "Replace downstream O2 sensor on Bank 2; check fuse and wiring",
    ),
    # ── Catalytic Converter ─────────────────────────────────────────────────────
    (
        "P0420",
        "Catalytic Converter",
        "Warning",
        "Catalyst System Efficiency Below Threshold (Bank 1)",
        "Check engine light, poor fuel economy, sulfur smell from exhaust",
        "Inspect for exhaust leaks before catalytic converter; replace catalytic converter; rule out engine misfires first as they damage cats",
    ),
    (
        "P0430",
        "Catalytic Converter",
        "Warning",
        "Catalyst System Efficiency Below Threshold (Bank 2)",
        "Check engine light, poor fuel economy, sulfur smell from exhaust (Bank 2)",
        "Inspect for exhaust leaks before catalytic converter on Bank 2; replace catalytic converter on Bank 2",
    ),
    # ── EVAP System ─────────────────────────────────────────────────────────────
    (
        "P0440",
        "EVAP",
        "Info",
        "Evaporative Emission Control System Malfunction",
        "Check engine light, fuel smell near vehicle, failed emissions test",
        "Inspect fuel cap for proper seal; check EVAP hoses and purge valve; test charcoal canister",
    ),
    (
        "P0441",
        "EVAP",
        "Info",
        "Evaporative Emission Control System Incorrect Purge Flow",
        "Check engine light, possible fuel smell",
        "Inspect and replace EVAP purge solenoid; check vacuum line to purge valve",
    ),
    (
        "P0442",
        "EVAP",
        "Info",
        "Evaporative Emission Control System Leak Detected (Small Leak)",
        "Check engine light, possible fuel odor",
        "Tighten or replace fuel cap; inspect EVAP hoses for cracks; use smoke test to locate leak",
    ),
    (
        "P0446",
        "EVAP",
        "Info",
        "Evaporative Emission Control System Vent Control Circuit Malfunction",
        "Check engine light, possible fuel smell",
        "Inspect EVAP vent valve; check wiring to vent solenoid; replace vent valve if faulty",
    ),
    (
        "P0455",
        "EVAP",
        "Info",
        "Evaporative Emission Control System Leak Detected (Large Leak)",
        "Strong fuel smell, check engine light",
        "Check fuel cap; inspect EVAP purge and vent valves; perform smoke test on EVAP system",
    ),
    (
        "P0456",
        "EVAP",
        "Info",
        "Evaporative Emission Control System Leak Detected (Very Small Leak)",
        "Check engine light, faint fuel odor",
        "Replace fuel cap first; inspect EVAP hoses and charcoal canister; use smoke machine for precise leak location",
    ),
    # ── EGR ─────────────────────────────────────────────────────────────────────
    (
        "P0401",
        "EGR",
        "Warning",
        "Exhaust Gas Recirculation (EGR) Flow Insufficient",
        "Rough idle, pinging or knocking under load, failed emissions test",
        "Clean or replace EGR valve; inspect EGR passages for carbon buildup; check DPFE sensor",
    ),
    (
        "P0402",
        "EGR",
        "Warning",
        "Exhaust Gas Recirculation (EGR) Flow Excessive",
        "Rough idle, stalling, black smoke, check engine light",
        "Inspect EGR valve for stuck-open condition; clean or replace EGR valve",
    ),
    (
        "P0404",
        "EGR",
        "Warning",
        "Exhaust Gas Recirculation (EGR) Circuit Range/Performance",
        "Rough idle, hesitation, check engine light",
        "Clean EGR valve pintle; replace EGR valve position sensor or full EGR assembly",
    ),
    # ── Speed / Transmission ────────────────────────────────────────────────────
    (
        "P0500",
        "Transmission",
        "Warning",
        "Vehicle Speed Sensor Malfunction",
        "Speedometer not working, harsh transmission shifts, ABS or traction control light on",
        "Inspect and replace vehicle speed sensor; check wiring harness and connectors",
    ),
    (
        "P0700",
        "Transmission",
        "Warning",
        "Transmission Control System Malfunction",
        "Harsh or erratic shifting, transmission stuck in gear, check engine light",
        "Connect a scanner to read transmission-specific codes; inspect transmission fluid level and condition; diagnose TCM or solenoids as directed by secondary codes",
    ),
    (
        "P0715",
        "Transmission",
        "Warning",
        "Input/Turbine Speed Sensor Circuit Malfunction",
        "Harsh shifting, transmission slipping, transmission warning light",
        "Replace input speed sensor; inspect transmission wiring harness",
    ),
    (
        "P0720",
        "Transmission",
        "Warning",
        "Output Speed Sensor Circuit Malfunction",
        "Erratic shifting, speedometer issues, limp mode",
        "Inspect output speed sensor and wiring; replace sensor",
    ),
    (
        "P0730",
        "Transmission",
        "Critical",
        "Incorrect Gear Ratio",
        "Slipping transmission, limp mode, transmission warning light",
        "Check transmission fluid condition; inspect solenoids; transmission service or rebuild may be required",
    ),
    (
        "P0740",
        "Transmission",
        "Warning",
        "Torque Converter Clutch Circuit Malfunction",
        "Poor fuel economy, shuddering at highway speed, overheating transmission",
        "Inspect TCC solenoid and wiring; check transmission fluid; replace torque converter if solenoid is OK",
    ),
    (
        "P0750",
        "Transmission",
        "Warning",
        "Shift Solenoid A Malfunction",
        "Harsh or incorrect shifting, limp mode, check engine light",
        "Replace shift solenoid A; check transmission fluid condition and level",
    ),
    # ── Battery / Charging ──────────────────────────────────────────────────────
    (
        "P0560",
        "Electrical",
        "Warning",
        "System Voltage Malfunction",
        "Dimming lights, erratic electrical behavior, check engine light",
        "Test battery and alternator; inspect for loose ground connections",
    ),
    (
        "P0562",
        "Electrical",
        "Warning",
        "System Voltage Low",
        "Dimming lights, slow cranking, electrical accessories malfunctioning",
        "Test and replace battery if weak; inspect alternator output; check for excessive parasitic drain",
    ),
    (
        "P0563",
        "Electrical",
        "Warning",
        "System Voltage High",
        "Battery overcharging, warning lights, possible damage to electrical components",
        "Test alternator voltage output; replace voltage regulator or alternator if overcharging",
    ),
    (
        "P0600",
        "Electrical",
        "Critical",
        "Serial Communication Link Malfunction",
        "Multiple warning lights, erratic gauge readings, modules not responding",
        "Inspect CAN bus wiring for damage; check ECU and module grounds; scan for module-specific DTCs",
    ),
    (
        "P0606",
        "Electrical",
        "Critical",
        "Control Module Processor Fault (ECM/PCM)",
        "Check engine light, drivability issues, possible no-start",
        "Check ECU grounds and power supply; update or replace ECU/PCM if internal fault confirmed",
    ),
    # ── Throttle / Pedal ────────────────────────────────────────────────────────
    (
        "P0120",
        "Throttle",
        "Warning",
        "Throttle/Pedal Position Sensor/Switch 'A' Circuit Malfunction",
        "Erratic acceleration, limp mode, stalling, rough idle",
        "Inspect TPS wiring and connectors; calibrate or replace throttle position sensor",
    ),
    (
        "P0121",
        "Throttle",
        "Warning",
        "Throttle/Pedal Position Sensor/Switch 'A' Circuit Range/Performance",
        "Hesitation, limp mode, erratic throttle response",
        "Inspect throttle body for carbon buildup; replace TPS sensor; check for binding throttle cable",
    ),
    (
        "P0122",
        "Throttle",
        "Warning",
        "Throttle/Pedal Position Sensor/Switch 'A' Circuit Low Input",
        "Limp mode, very poor acceleration, check engine light",
        "Inspect TPS wiring for short to ground; replace TPS sensor",
    ),
    (
        "P0123",
        "Throttle",
        "Warning",
        "Throttle/Pedal Position Sensor/Switch 'A' Circuit High Input",
        "Limp mode, poor acceleration, check engine light",
        "Inspect TPS wiring for open circuit; replace TPS sensor",
    ),
    (
        "P0505",
        "Throttle",
        "Warning",
        "Idle Control System Malfunction",
        "Erratic or high idle, stalling at idle",
        "Clean or replace idle air control (IAC) valve; check for vacuum leaks; inspect throttle body",
    ),
    (
        "P0507",
        "Throttle",
        "Warning",
        "Idle Control System RPM High",
        "Engine idling too high (above 200 RPM over target)",
        "Inspect for vacuum leaks; clean throttle body; check IAC valve or electronic throttle control",
    ),
    # ── Cooling ─────────────────────────────────────────────────────────────────
    (
        "P0115",
        "Cooling",
        "Warning",
        "Engine Coolant Temperature Sensor 1 Circuit Malfunction",
        "Engine overheating warning, poor fuel economy, hard starting when cold",
        "Inspect coolant temperature sensor wiring; replace coolant temperature sensor",
    ),
    (
        "P0116",
        "Cooling",
        "Warning",
        "Engine Coolant Temperature Sensor 1 Circuit Range/Performance",
        "Poor fuel economy, inaccurate temperature gauge, rough cold start",
        "Inspect coolant temperature sensor; check cooling system for air pockets; replace sensor",
    ),
    (
        "P0217",
        "Cooling",
        "Critical",
        "Engine Over Temperature Condition",
        "Temperature gauge in red zone, steam from engine bay, coolant warning light",
        "Stop vehicle immediately; check coolant level; inspect for coolant leaks, faulty thermostat, or failed water pump",
    ),
    (
        "P0218",
        "Cooling",
        "Critical",
        "Transmission Fluid Over Temperature Condition",
        "Transmission warning light, overheating smell, limp mode",
        "Check transmission fluid level and condition; inspect transmission cooler lines; add external cooler if towing",
    ),
    # ── Oil / Pressure ──────────────────────────────────────────────────────────
    (
        "P0520",
        "Oil",
        "Warning",
        "Engine Oil Pressure Sensor/Switch Circuit Malfunction",
        "Oil pressure warning light, suspected low oil pressure reading",
        "Check engine oil level; inspect oil pressure sensor and wiring; replace sensor; if oil pressure is genuinely low, diagnose oil pump",
    ),
    (
        "P0521",
        "Oil",
        "Warning",
        "Engine Oil Pressure Sensor/Switch Range/Performance",
        "Fluctuating oil pressure gauge, oil pressure warning",
        "Check oil level and viscosity; inspect oil pressure sensor; test actual oil pressure mechanically",
    ),
    (
        "P0522",
        "Oil",
        "Critical",
        "Engine Oil Pressure Sensor/Switch Low Voltage",
        "Oil pressure warning light on, check engine light",
        "Inspect sensor wiring for short to ground; replace oil pressure sensor",
    ),
    # ── ABS / Brakes ────────────────────────────────────────────────────────────
    (
        "C0031",
        "ABS & Brakes",
        "Critical",
        "Right Front Wheel Speed Sensor Circuit Malfunction",
        "ABS warning light, traction control light, ABS not functioning",
        "Inspect right front wheel speed sensor and wiring; replace sensor; check reluctor ring for damage",
    ),
    (
        "C0034",
        "ABS & Brakes",
        "Critical",
        "Right Rear Wheel Speed Sensor Circuit Malfunction",
        "ABS warning light, traction control light, ABS not functioning",
        "Inspect right rear wheel speed sensor and wiring; replace sensor; check reluctor ring for damage",
    ),
    (
        "C0035",
        "ABS & Brakes",
        "Critical",
        "Left Front Wheel Speed Sensor Circuit Malfunction",
        "ABS warning light, traction control light, ABS not functioning",
        "Inspect left front wheel speed sensor and wiring; replace sensor; check reluctor ring",
    ),
    (
        "C0040",
        "ABS & Brakes",
        "Critical",
        "Right Front Wheel Speed Sensor Signal Fault",
        "ABS warning light, erratic speedometer",
        "Inspect wheel speed sensor mounting and gap; check for metallic debris on reluctor ring",
    ),
    (
        "C0265",
        "ABS & Brakes",
        "Critical",
        "ABS Actuator Relay Circuit Open",
        "ABS and stability control warning lights, ABS disabled",
        "Inspect ABS relay and fuse; check wiring to ABS module; replace relay or ABS module",
    ),
    # ── More ABS & Brakes ──────────────────────────────────────────────────────
    (
        "C0036",
        "ABS & Brakes",
        "Critical",
        "Left Rear Wheel Speed Sensor Circuit Malfunction",
        "ABS warning light, traction control light, ABS not functioning",
        "Inspect left rear wheel speed sensor and wiring; replace sensor; check reluctor ring for damage",
    ),
    (
        "C0041",
        "ABS & Brakes",
        "Critical",
        "Right Front Wheel Speed Sensor Signal Fault",
        "ABS warning light, erratic ABS engagement, speedometer fluctuation",
        "Check wheel speed sensor air gap and reluctor ring teeth; clean sensor face; replace sensor if signal absent",
    ),
    (
        "C0046",
        "ABS & Brakes",
        "Critical",
        "Left Front Wheel Speed Sensor Signal Fault",
        "ABS warning light, loss of traction control, stability control disabled",
        "Check sensor mounting bracket and reluctor ring; clean debris; replace sensor if waveform is erratic",
    ),
    (
        "C0047",
        "ABS & Brakes",
        "Critical",
        "Left Rear Wheel Speed Sensor Signal Fault",
        "ABS warning light, ABS activating at low speed, stability control fault",
        "Inspect sensor air gap and reluctor ring; replace wheel speed sensor or reluctor ring if damaged",
    ),
    (
        "C0110",
        "ABS & Brakes",
        "Critical",
        "ABS Pump Motor Circuit Malfunction",
        "ABS and stability control warning lights, ABS and TCS disabled",
        "Check ABS pump motor fuse and relay; inspect motor wiring; replace ABS hydraulic unit if motor has failed",
    ),
    (
        "C0121",
        "ABS & Brakes",
        "Critical",
        "ABS Valve Relay Circuit Malfunction",
        "ABS warning light, ABS disabled, longer stopping distances",
        "Inspect ABS valve relay and associated fuse; check wiring harness to ABS module; replace relay or ABS module",
    ),
    (
        "C0161",
        "ABS & Brakes",
        "Critical",
        "ABS/TCS Brake Switch Circuit Malfunction",
        "ABS or traction control not functioning properly, warning lights illuminated",
        "Inspect brake light switch and its wiring; replace brake light switch; check fuse",
    ),
    (
        "C0196",
        "ABS & Brakes",
        "Critical",
        "Yaw Rate Sensor Circuit Malfunction",
        "Stability control warning light, ESC disabled, pulling during cornering",
        "Inspect yaw rate sensor connector and wiring; calibrate or replace yaw rate sensor",
    ),
    (
        "C0245",
        "ABS & Brakes",
        "Critical",
        "Wheel Speed Sensor Frequency Error",
        "ABS warning light, inconsistent ABS activation",
        "Inspect reluctor ring for missing or damaged teeth; check sensor air gap; replace sensor or reluctor ring",
    ),
    (
        "C0550",
        "ABS & Brakes",
        "Critical",
        "ABS Electronic Control Unit Malfunction",
        "ABS, TCS, and stability control all disabled, multiple warning lights",
        "Check power and ground to ABS module; inspect wiring harness; replace ABS control module if internal fault confirmed",
    ),
    # ── Steering ────────────────────────────────────────────────────────────────
    (
        "C0460",
        "Steering",
        "Critical",
        "Steering Angle Sensor Circuit Malfunction",
        "Stability control warning light, ESC disabled, steering warning light",
        "Inspect steering angle sensor connector; replace sensor; re-calibrate after replacement with scan tool",
    ),
    (
        "C0461",
        "Steering",
        "Critical",
        "Steering Angle Sensor Circuit Range/Performance",
        "ESC and traction control warning lights, steering feel may change",
        "Perform steering angle sensor calibration (lock-to-lock); replace sensor if calibration fails",
    ),
    (
        "C0485",
        "Steering",
        "Critical",
        "Steering Assist Control Actuator Failure",
        "Heavy steering, power steering warning light, reduced steering assist",
        "Check power steering control module for fault codes; inspect motor wiring; replace electric power steering motor or module",
    ),
    (
        "C0490",
        "Steering",
        "Critical",
        "Electronic Power Steering (EPS) System Fault",
        "Power steering warning light, steering is heavy especially at low speed",
        "Check EPS module fuse and power supply; update EPS control module software; replace EPS module or motor assembly",
    ),
    # ── Variable Valve Timing ───────────────────────────────────────────────────
    (
        "P0010",
        "Variable Valve Timing",
        "Warning",
        '"A" Camshaft Position Actuator Circuit Malfunction (Bank 1)',
        "Rough idle, poor fuel economy, check engine light, reduced power",
        "Check VVT solenoid valve wiring; clean or replace VVT oil control solenoid; inspect for sludge buildup in oil passages",
    ),
    (
        "P0011",
        "Variable Valve Timing",
        "Warning",
        '"A" Camshaft Position Timing Over-Advanced or System Performance (Bank 1)',
        "Rough idle at cold start, rattling at startup, poor fuel economy, check engine light",
        "Change engine oil and filter; clean VVT solenoid screen; replace VVT solenoid; inspect timing chain for stretch",
    ),
    (
        "P0012",
        "Variable Valve Timing",
        "Warning",
        '"A" Camshaft Position Timing Over-Retarded (Bank 1)',
        "Hard starting, poor idle, lack of power, check engine light",
        "Change engine oil and filter; clean or replace VVT oil control valve; inspect timing chain and tensioner",
    ),
    (
        "P0013",
        "Variable Valve Timing",
        "Warning",
        '"B" Camshaft Position Actuator Circuit Malfunction (Bank 1)',
        "Rough idle, poor performance, check engine light",
        "Inspect VVT solenoid wiring and connector; replace exhaust camshaft VVT solenoid (Bank 1)",
    ),
    (
        "P0014",
        "Variable Valve Timing",
        "Warning",
        '"B" Camshaft Position Timing Over-Advanced or System Performance (Bank 1)',
        "Rough idle, engine rattle at startup, poor fuel economy",
        "Change oil and filter; clean VVT solenoid screen; replace exhaust cam VVT solenoid; check timing chain",
    ),
    (
        "P0015",
        "Variable Valve Timing",
        "Warning",
        '"B" Camshaft Position Timing Over-Retarded (Bank 1)',
        "Hard cold start, poor power, rough idle, check engine light",
        "Change engine oil; clean or replace exhaust cam VVT solenoid; inspect timing chain and cam phaser",
    ),
    (
        "P0016",
        "Variable Valve Timing",
        "Warning",
        "Crankshaft Position to Camshaft Position Correlation (Bank 1, Sensor A)",
        "Engine crank but no-start, rough running, check engine light",
        "Inspect timing chain for stretch or skipped teeth; replace timing chain kit; check cam and crank reluctor rings",
    ),
    (
        "P0017",
        "Variable Valve Timing",
        "Warning",
        "Crankshaft Position to Camshaft B Position Correlation (Bank 1)",
        "Rough running, difficult to start, check engine light",
        "Inspect timing chain; replace timing chain and guides; verify cam phaser operation",
    ),
    (
        "P0020",
        "Variable Valve Timing",
        "Warning",
        '"A" Camshaft Position Actuator Circuit Malfunction (Bank 2)',
        "Rough idle, poor fuel economy, check engine light",
        "Check VVT solenoid wiring on Bank 2; clean or replace VVT oil control solenoid; check oil level and quality",
    ),
    (
        "P0021",
        "Variable Valve Timing",
        "Warning",
        '"A" Camshaft Position Timing Over-Advanced or System Performance (Bank 2)',
        "Rough idle, rattling at cold start, check engine light",
        "Change engine oil; clean or replace VVT solenoid on Bank 2; inspect timing chain",
    ),
    (
        "P0022",
        "Variable Valve Timing",
        "Warning",
        '"A" Camshaft Position Timing Over-Retarded (Bank 2)',
        "Hard starting, poor idle, reduced power, check engine light",
        "Change engine oil; replace VVT solenoid on Bank 2; inspect timing chain and tensioner",
    ),
    # ── Crankshaft / Camshaft Position Sensors ─────────────────────────────────
    (
        "P0335",
        "Crankshaft & Camshaft",
        "Warning",
        'Crankshaft Position Sensor "A" Circuit Malfunction',
        "No start or intermittent stall, engine cranks but won't fire, check engine light",
        "Inspect CKP sensor wiring and connector for damage; replace crankshaft position sensor; check reluctor wheel for missing teeth",
    ),
    (
        "P0336",
        "Crankshaft & Camshaft",
        "Warning",
        'Crankshaft Position Sensor "A" Circuit Range/Performance',
        "Intermittent stalling, rough running, engine hesitation",
        "Check CKP sensor air gap; inspect reluctor ring; replace crankshaft position sensor",
    ),
    (
        "P0337",
        "Crankshaft & Camshaft",
        "Warning",
        'Crankshaft Position Sensor "A" Circuit Low Input',
        "Engine stalls or won't start, no tachometer reading",
        "Inspect sensor wiring for short to ground; replace crankshaft position sensor",
    ),
    (
        "P0338",
        "Crankshaft & Camshaft",
        "Warning",
        'Crankshaft Position Sensor "A" Circuit High Input',
        "Engine stalls or won't start, erratic tachometer",
        "Inspect sensor wiring for open circuit or short to voltage; replace crankshaft position sensor",
    ),
    (
        "P0340",
        "Crankshaft & Camshaft",
        "Warning",
        'Camshaft Position Sensor "A" Circuit Malfunction (Bank 1)',
        "No start, stalling, rough running, check engine light",
        "Inspect CMP sensor wiring and connector; replace camshaft position sensor (Bank 1 intake); check tone wheel",
    ),
    (
        "P0341",
        "Crankshaft & Camshaft",
        "Warning",
        'Camshaft Position Sensor "A" Circuit Range/Performance (Bank 1)',
        "Hard starting, rough idle, poor power, timing-related issues",
        "Inspect CMP sensor air gap and tone wheel; replace camshaft position sensor; check timing chain for stretch",
    ),
    (
        "P0345",
        "Crankshaft & Camshaft",
        "Warning",
        'Camshaft Position Sensor "A" Circuit Malfunction (Bank 2)',
        "No start, stalling, rough running on Bank 2 side",
        "Inspect CMP sensor wiring on Bank 2; replace camshaft position sensor (Bank 2 intake)",
    ),
    (
        "P0346",
        "Crankshaft & Camshaft",
        "Warning",
        'Camshaft Position Sensor "A" Circuit Range/Performance (Bank 2)',
        "Hard starting, rough idle, timing issues on V-engine Bank 2",
        "Inspect sensor air gap and tone wheel on Bank 2; replace camshaft position sensor; inspect timing chain",
    ),
    # ── Knock Sensor ────────────────────────────────────────────────────────────
    (
        "P0325",
        "Knock Sensor",
        "Warning",
        "Knock Sensor 1 Circuit Malfunction (Bank 1 or Single Sensor)",
        "Check engine light, potential engine pinging under load, reduced performance (ECU retards timing as precaution)",
        "Inspect knock sensor wiring harness and connector; replace knock sensor; re-torque sensor to spec (over-tightening causes false reads)",
    ),
    (
        "P0326",
        "Knock Sensor",
        "Warning",
        "Knock Sensor 1 Circuit Range/Performance (Bank 1 or Single Sensor)",
        "Check engine light, slight reduction in power or fuel economy",
        "Check sensor mounting and torque; inspect wiring for chafing; replace knock sensor",
    ),
    (
        "P0327",
        "Knock Sensor",
        "Warning",
        "Knock Sensor 1 Circuit Low Input (Bank 1 or Single Sensor)",
        "Check engine light, possible engine pinging, reduced power under load",
        "Inspect wiring for short to ground; replace knock sensor; verify correct sensor for application",
    ),
    (
        "P0328",
        "Knock Sensor",
        "Warning",
        "Knock Sensor 1 Circuit High Input (Bank 1 or Single Sensor)",
        "Check engine light, ECU may retard timing causing poor performance",
        "Inspect wiring for open circuit; replace knock sensor; check PCM knock input functionality",
    ),
    (
        "P0330",
        "Knock Sensor",
        "Warning",
        "Knock Sensor 2 Circuit Malfunction (Bank 2)",
        "Check engine light on V-engine, pinging under load (Bank 2 side), reduced power",
        "Inspect Bank 2 knock sensor wiring and connector; replace knock sensor; re-torque to spec",
    ),
    (
        "P0331",
        "Knock Sensor",
        "Warning",
        "Knock Sensor 2 Circuit Range/Performance (Bank 2)",
        "Check engine light, slight power reduction, possible pinging",
        "Check sensor mounting torque on Bank 2; replace knock sensor; inspect wiring harness routing",
    ),
    (
        "P0332",
        "Knock Sensor",
        "Warning",
        "Knock Sensor 2 Circuit Low Input (Bank 2)",
        "Check engine light, pinging under load on Bank 2",
        "Inspect wiring for short to ground on Bank 2 knock sensor circuit; replace knock sensor",
    ),
    (
        "P0333",
        "Knock Sensor",
        "Warning",
        "Knock Sensor 2 Circuit High Input (Bank 2)",
        "Check engine light, timing retard on Bank 2, reduced fuel economy",
        "Inspect wiring for open circuit on Bank 2; replace knock sensor; verify PCM operation",
    ),
    # ── Fuel Injectors ──────────────────────────────────────────────────────────
    (
        "P0201",
        "Fuel Injectors",
        "Warning",
        "Cylinder 1 Injector Circuit Malfunction",
        "Misfire on cylinder 1, rough idle, fuel smell, check engine light",
        "Inspect cylinder 1 injector wiring and connector; test injector resistance; replace injector or injector driver if PCM output is faulty",
    ),
    (
        "P0202",
        "Fuel Injectors",
        "Warning",
        "Cylinder 2 Injector Circuit Malfunction",
        "Misfire on cylinder 2, rough idle, fuel smell, check engine light",
        "Inspect cylinder 2 injector wiring; test injector resistance (typically 11–17 Ω); replace injector if shorted or open",
    ),
    (
        "P0203",
        "Fuel Injectors",
        "Warning",
        "Cylinder 3 Injector Circuit Malfunction",
        "Misfire on cylinder 3, rough idle, check engine light",
        "Inspect injector connector and wiring for cylinder 3; swap injector with known-good to isolate fault; replace as needed",
    ),
    (
        "P0204",
        "Fuel Injectors",
        "Warning",
        "Cylinder 4 Injector Circuit Malfunction",
        "Misfire on cylinder 4, rough idle, check engine light",
        "Inspect cylinder 4 injector connector; test injector resistance; replace injector or address PCM driver fault",
    ),
    (
        "P0205",
        "Fuel Injectors",
        "Warning",
        "Cylinder 5 Injector Circuit Malfunction",
        "Misfire on cylinder 5 (V6/V8), rough idle, check engine light",
        "Inspect injector wiring on cylinder 5; swap and test injector; replace injector or address wiring fault",
    ),
    (
        "P0206",
        "Fuel Injectors",
        "Warning",
        "Cylinder 6 Injector Circuit Malfunction",
        "Misfire on cylinder 6, rough idle, check engine light",
        "Inspect cylinder 6 injector wiring and connector; replace injector if resistance out of spec",
    ),
    (
        "P0261",
        "Fuel Injectors",
        "Warning",
        "Cylinder 1 Injector Circuit Low",
        "Misfire or no-fire on cylinder 1, rough running, fuel trim lean on Bank 1",
        "Check injector wiring for short to ground; inspect PCM injector driver output; replace injector or repair wiring",
    ),
    (
        "P0264",
        "Fuel Injectors",
        "Warning",
        "Cylinder 2 Injector Circuit Low",
        "Misfire on cylinder 2, rough running, lean trim",
        "Check injector wiring for short to ground on cylinder 2; replace injector or repair harness",
    ),
    (
        "P0267",
        "Fuel Injectors",
        "Warning",
        "Cylinder 3 Injector Circuit Low",
        "Misfire on cylinder 3, rough idle, lean fuel trim",
        "Check injector connector and wiring for short to ground on cylinder 3; replace injector",
    ),
    (
        "P0270",
        "Fuel Injectors",
        "Warning",
        "Cylinder 4 Injector Circuit Low",
        "Misfire on cylinder 4, rough running, check engine light",
        "Inspect injector wiring for short to ground on cylinder 4; replace injector as needed",
    ),
    # ── Fuel Pressure ───────────────────────────────────────────────────────────
    (
        "P0087",
        "Fuel & Air",
        "Warning",
        "Fuel Rail/System Pressure Too Low",
        "Hard starting, stalling under load, hesitation during acceleration, poor performance",
        "Check fuel pump pressure; replace fuel pump or fuel filter; inspect fuel pressure regulator; check for kinked fuel lines",
    ),
    (
        "P0088",
        "Fuel & Air",
        "Critical",
        "Fuel Rail/System Pressure Too High",
        "Rich running condition, engine flooding, black smoke, fuel smell, poor fuel economy",
        "Replace fuel pressure regulator; inspect fuel return line for restriction; check fuel pressure sensor accuracy",
    ),
    (
        "P0089",
        "Fuel & Air",
        "Warning",
        "Fuel Pressure Regulator 1 Performance",
        "Inconsistent fuel pressure, rough idle, hesitation, check engine light",
        "Inspect fuel pressure regulator vacuum line; replace fuel pressure regulator; check fuel pump volume",
    ),
    (
        "P0090",
        "Fuel & Air",
        "Warning",
        "Fuel Pressure Regulator 1 Control Circuit Malfunction",
        "Poor idle quality, erratic performance, check engine light",
        "Inspect fuel pressure regulator control solenoid wiring; replace solenoid or regulator assembly",
    ),
    (
        "P0091",
        "Fuel & Air",
        "Warning",
        "Fuel Pressure Regulator 1 Control Circuit Low",
        "Engine stalls, hard starting, poor fuel delivery",
        "Check for short to ground in fuel pressure regulator circuit; replace solenoid or repair harness",
    ),
    (
        "P0092",
        "Fuel & Air",
        "Warning",
        "Fuel Pressure Regulator 1 Control Circuit High",
        "Rich running, fuel smell, poor idle",
        "Check for open circuit or short to voltage in regulator circuit; replace solenoid; inspect PCM driver",
    ),
    (
        "P0192",
        "Fuel & Air",
        "Warning",
        "Fuel Rail Pressure Sensor Circuit Low Input",
        "Hard starting, stalling, poor acceleration, check engine light",
        "Inspect fuel rail pressure sensor wiring for short to ground; replace fuel rail pressure sensor",
    ),
    (
        "P0193",
        "Fuel & Air",
        "Warning",
        "Fuel Rail Pressure Sensor Circuit High Input",
        "Hard starting, rough idle, check engine light, possible reduced power mode",
        "Inspect sensor wiring for open circuit or short to voltage; replace fuel rail pressure sensor",
    ),
    # ── Turbocharger / Supercharger ─────────────────────────────────────────────
    (
        "P0234",
        "Turbocharger",
        "Critical",
        'Turbocharger/Supercharger "A" Overboost Condition',
        "Check engine light, engine may go into limp mode, excessive boost pressure warning",
        "Inspect wastegate actuator and solenoid; check boost control solenoid; inspect charge pipes for leaks; replace wastegate if stuck closed",
    ),
    (
        "P0235",
        "Turbocharger",
        "Warning",
        'Turbocharger/Supercharger Boost Sensor "A" Circuit Malfunction',
        "Check engine light, limp mode, inconsistent boost pressure",
        "Inspect MAP/boost pressure sensor wiring and connector; replace boost pressure sensor; check reference voltage",
    ),
    (
        "P0236",
        "Turbocharger",
        "Warning",
        'Turbocharger/Supercharger Boost Sensor "A" Circuit Range/Performance',
        "Check engine light, boost pressure not matching expected values, reduced power",
        "Inspect boost sensor and vacuum hoses; check for boost leaks; replace sensor if reading is out of range",
    ),
    (
        "P0237",
        "Turbocharger",
        "Warning",
        'Turbocharger/Supercharger Boost Sensor "A" Circuit Low',
        "Limp mode, poor performance, check engine light",
        "Check boost sensor wiring for short to ground; replace boost pressure sensor",
    ),
    (
        "P0238",
        "Turbocharger",
        "Warning",
        'Turbocharger/Supercharger Boost Sensor "A" Circuit High',
        "Limp mode, engine over-boosting, check engine light",
        "Check boost sensor wiring for open circuit; replace boost pressure sensor",
    ),
    (
        "P0243",
        "Turbocharger",
        "Warning",
        'Turbocharger/Supercharger Wastegate Solenoid "A" Malfunction',
        "Boost too high or too low, poor performance, check engine light",
        "Inspect wastegate solenoid wiring; replace boost control solenoid; check pneumatic lines to wastegate actuator",
    ),
    (
        "P0244",
        "Turbocharger",
        "Warning",
        'Turbocharger/Supercharger Wastegate Solenoid "A" Range/Performance',
        "Inconsistent boost pressure, reduced power, check engine light",
        "Inspect wastegate solenoid operation; check duty cycle with scan tool; replace solenoid if not responding correctly",
    ),
    (
        "P0299",
        "Turbocharger",
        "Warning",
        'Turbocharger/Supercharger "A" Underboost Condition',
        "Lack of power, sluggish acceleration, check engine light, boost pressure low",
        "Check for boost leaks in charge pipes and intercooler; inspect wastegate (may be stuck open); check turbo vanes for carbon buildup; replace turbocharger if bearing failure confirmed",
    ),
    # ── Secondary Air Injection ─────────────────────────────────────────────────
    (
        "P0410",
        "Secondary Air Injection",
        "Info",
        "Secondary Air Injection System Malfunction",
        "Failed emissions test, check engine light, higher cold-start emissions",
        "Inspect air injection pump; check one-way check valve for failure; inspect hoses and solenoid; replace air pump if seized",
    ),
    (
        "P0411",
        "Secondary Air Injection",
        "Info",
        "Secondary Air Injection System Incorrect Flow Detected",
        "Check engine light, emissions test failure; no driveability symptoms usually",
        "Check one-way check valves for clogging or backflow; inspect air pump output; clean or replace check valves and pump",
    ),
    (
        "P0412",
        "Secondary Air Injection",
        "Info",
        "Secondary Air Injection Switching Valve Circuit Malfunction",
        "Check engine light, secondary air system not activating properly",
        "Inspect air injection solenoid valve wiring; replace secondary air switching solenoid valve",
    ),
    (
        "P0413",
        "Secondary Air Injection",
        "Info",
        "Secondary Air Injection Switching Valve Circuit Open",
        "Check engine light, secondary air system inoperative",
        "Inspect wiring for open circuit to air injection switching solenoid; replace solenoid or repair harness",
    ),
    # ── More Ignition Coils ─────────────────────────────────────────────────────
    (
        "P0353",
        "Ignition",
        "Warning",
        'Ignition Coil "C" Primary/Secondary Circuit Malfunction',
        "Misfire on cylinder 3, rough idle, check engine light, possible raw fuel smell",
        "Swap coil C with a known-good coil to confirm fault follows; replace ignition coil C; inspect spark plug and wiring",
    ),
    (
        "P0354",
        "Ignition",
        "Warning",
        'Ignition Coil "D" Primary/Secondary Circuit Malfunction',
        "Misfire on cylinder 4, rough idle, check engine light",
        "Swap coil D to confirm; replace ignition coil D; inspect spark plug and boot",
    ),
    (
        "P0355",
        "Ignition",
        "Warning",
        'Ignition Coil "E" Primary/Secondary Circuit Malfunction',
        "Misfire on cylinder 5 (V6/V8/V10), rough idle, check engine light",
        "Swap coil E to confirm; replace ignition coil E; inspect spark plug",
    ),
    (
        "P0356",
        "Ignition",
        "Warning",
        'Ignition Coil "F" Primary/Secondary Circuit Malfunction',
        "Misfire on cylinder 6, rough idle, check engine light",
        "Swap coil F to confirm; replace ignition coil F; inspect spark plug",
    ),
    (
        "P0357",
        "Ignition",
        "Warning",
        'Ignition Coil "G" Primary/Secondary Circuit Malfunction',
        "Misfire on cylinder 7 (V8/V10/V12), rough idle, check engine light",
        "Swap coil G to confirm; replace ignition coil G; inspect spark plug and high-voltage cap",
    ),
    (
        "P0358",
        "Ignition",
        "Warning",
        'Ignition Coil "H" Primary/Secondary Circuit Malfunction',
        "Misfire on cylinder 8, rough idle, check engine light, poor power on V8",
        "Swap coil H to confirm misfire follows; replace ignition coil H; inspect spark plug",
    ),
    # ── A/C & Climate ──────────────────────────────────────────────────────────
    (
        "P0530",
        "A/C & Climate",
        "Info",
        "A/C Refrigerant Pressure Sensor Circuit Malfunction",
        "A/C not working, compressor not engaging, check engine light",
        "Inspect A/C pressure sensor wiring and connector; check refrigerant charge level; replace A/C pressure sensor",
    ),
    (
        "P0531",
        "A/C & Climate",
        "Info",
        "A/C Refrigerant Pressure Sensor Circuit Range/Performance",
        "A/C compressor cycling erratically, check engine light, A/C blowing warm",
        "Check refrigerant pressure against spec; inspect sensor for contamination; replace A/C pressure sensor",
    ),
    (
        "P0532",
        "A/C & Climate",
        "Warning",
        "A/C Refrigerant Pressure Sensor Circuit Low Input",
        "A/C compressor disabled, A/C blowing warm, check engine light",
        "Check sensor wiring for short to ground; verify refrigerant charge is not too low; replace A/C pressure sensor",
    ),
    (
        "P0533",
        "A/C & Climate",
        "Warning",
        "A/C Refrigerant Pressure Sensor Circuit High Input",
        "A/C compressor may not engage, check engine light",
        "Check sensor wiring for open circuit; verify refrigerant is not overcharged; replace A/C pressure sensor",
    ),
    (
        "P0534",
        "A/C & Climate",
        "Info",
        "A/C Refrigerant Charge Loss",
        "A/C blowing warm only, compressor cycling rapidly, check engine light",
        "Perform UV dye or electronic leak test; repair refrigerant leak; recharge A/C system to spec",
    ),
    # ── More Cooling ────────────────────────────────────────────────────────────
    (
        "P0117",
        "Cooling",
        "Warning",
        "Engine Coolant Temperature Sensor Circuit Low Input",
        "Engine may run rich (PCM thinks engine is cold), black smoke, poor fuel economy",
        "Inspect ECT sensor wiring for short to ground; replace engine coolant temperature sensor",
    ),
    (
        "P0118",
        "Cooling",
        "Warning",
        "Engine Coolant Temperature Sensor Circuit High Input",
        "Engine may run lean or poorly (PCM thinks engine is always hot), hard cold start",
        "Inspect ECT sensor wiring for open circuit; replace engine coolant temperature sensor",
    ),
    (
        "P0119",
        "Cooling",
        "Warning",
        "Engine Coolant Temperature Sensor Circuit Intermittent",
        "Erratic temperature gauge, intermittent check engine light, occasional poor running",
        "Inspect ECT sensor connector for corrosion; replace ECT sensor; check wiring harness for intermittent short",
    ),
    (
        "P0125",
        "Cooling",
        "Warning",
        "Insufficient Coolant Temperature for Closed Loop Fuel Control",
        "Poor fuel economy, heater takes too long to warm up, engine runs cold for extended period",
        "Replace engine thermostat (stuck open); inspect ECT sensor accuracy; check coolant level",
    ),
    # ── More Oil ────────────────────────────────────────────────────────────────
    (
        "P0523",
        "Oil",
        "Critical",
        "Engine Oil Pressure Sensor/Switch Circuit High",
        "Oil warning light on or off erratically, check engine light",
        "Inspect oil pressure sensor wiring for open circuit or short to voltage; replace oil pressure sensor/switch",
    ),
    (
        "P0524",
        "Oil",
        "Critical",
        "Engine Oil Pressure Too Low",
        "Oil pressure warning light, engine knocking, potential engine damage",
        "Check oil level immediately; if oil level is OK, inspect oil pressure sensor; check oil pump; stop driving to avoid engine damage",
    ),
    # ── More Electrical / PCM ───────────────────────────────────────────────────
    (
        "P0601",
        "Electrical",
        "Critical",
        "Internal Control Module Memory Check Sum Error",
        "Multiple seemingly unrelated codes, erratic engine behavior, check engine light",
        "Attempt PCM software update (reflash); replace PCM if checksum failure persists; verify correct PCM calibration for vehicle",
    ),
    (
        "P0602",
        "Electrical",
        "Critical",
        "Control Module Programming Error",
        "Engine does not start, multiple fault codes, immobilizer active",
        "Reprogram or reflash PCM using manufacturer scan tool; replace PCM if programming fails repeatedly",
    ),
    (
        "P0603",
        "Electrical",
        "Critical",
        "Internal Control Module Keep Alive Memory (KAM) Error",
        "Loss of learned idle and fuel trim settings, rough idle after battery disconnect, check engine light",
        "Disconnect battery for 15 minutes; reconnect and perform idle relearn procedure; replace PCM if KAM error persists",
    ),
    (
        "P0604",
        "Electrical",
        "Critical",
        "Internal Control Module RAM Error",
        "Erratic engine operation, false trouble codes, check engine light",
        "Attempt PCM reflash; replace PCM if RAM error persists after reprogramming",
    ),
    (
        "P0605",
        "Electrical",
        "Critical",
        "Internal Control Module ROM Error",
        "No start or severe drivability issues, check engine light",
        "Reflash PCM with latest software; replace PCM if ROM error cannot be corrected",
    ),
    (
        "P0607",
        "Electrical",
        "Critical",
        "Control Module Performance",
        "Check engine light, various system malfunctions, possible limp mode",
        "Check PCM power supply and ground connections; update PCM software; replace PCM if fault persists",
    ),
    (
        "P0610",
        "Electrical",
        "Critical",
        "Control Module Vehicle Options Error",
        "Check engine light, certain vehicle features not working correctly",
        "Reprogram PCM with correct vehicle option configuration; replace PCM if options cannot be programmed",
    ),
    # ── More Transmission ───────────────────────────────────────────────────────
    (
        "P0705",
        "Transmission",
        "Warning",
        "Transmission Range Sensor Circuit Malfunction (PRNDL Input)",
        "Transmission may not shift out of park, incorrect gear indicator, no reverse lights",
        "Inspect transmission range sensor (neutral safety switch) wiring; adjust or replace range sensor",
    ),
    (
        "P0706",
        "Transmission",
        "Warning",
        "Transmission Range Sensor Circuit Range/Performance",
        "Incorrect gear display, erratic shifting, transmission fault light",
        "Check range sensor adjustment; replace transmission range sensor if reading is erratic",
    ),
    (
        "P0710",
        "Transmission",
        "Warning",
        "Transmission Fluid Temperature Sensor Circuit Malfunction",
        "Transmission fault light, harsh or erratic shifting especially when cold",
        "Inspect TFT sensor wiring and connector; replace transmission fluid temperature sensor",
    ),
    (
        "P0711",
        "Transmission",
        "Warning",
        "Transmission Fluid Temperature Sensor Circuit Range/Performance",
        "Transmission shifting harshly or not warming up normally, transmission fault light",
        "Check TFT sensor resistance against spec; replace sensor; check transmission fluid level and condition",
    ),
    (
        "P0712",
        "Transmission",
        "Warning",
        "Transmission Fluid Temperature Sensor Circuit Low Input",
        "Harsh cold shifts, transmission fault light",
        "Inspect TFT sensor wiring for short to ground; replace sensor",
    ),
    (
        "P0713",
        "Transmission",
        "Warning",
        "Transmission Fluid Temperature Sensor Circuit High Input",
        "Transmission overheating warning, harsh shifts, fault light",
        "Inspect TFT sensor wiring for open circuit; replace sensor; check transmission fluid level",
    ),
    (
        "P0716",
        "Transmission",
        "Warning",
        "Input/Turbine Speed Sensor Circuit Range/Performance",
        "Erratic shift timing, transmission slipping, fault light",
        "Inspect turbine speed sensor wiring; replace input shaft speed sensor; check transmission fluid condition",
    ),
    (
        "P0717",
        "Transmission",
        "Warning",
        "Input/Turbine Speed Sensor Circuit No Signal",
        "Transmission won't shift, stuck in one gear, fault light",
        "Replace input turbine speed sensor; inspect wiring; check flywheel/flexplate tone ring",
    ),
    (
        "P0721",
        "Transmission",
        "Warning",
        "Output Speed Sensor Circuit Range/Performance",
        "Erratic speedometer, harsh or no shifts, transmission fault light",
        "Inspect output speed sensor wiring and connector; replace output shaft speed sensor",
    ),
    (
        "P0722",
        "Transmission",
        "Warning",
        "Output Speed Sensor Circuit No Signal",
        "Speedometer inoperative, transmission stuck in gear, fault light",
        "Replace output shaft speed sensor; inspect tone ring on output shaft for damage; check wiring",
    ),
    (
        "P0731",
        "Transmission",
        "Warning",
        "Gear 1 Incorrect Ratio",
        "Slipping in first gear, harsh engagement, transmission fault light",
        "Check transmission fluid level and condition; inspect 1st gear clutch packs and bands; rebuild or replace transmission",
    ),
    (
        "P0732",
        "Transmission",
        "Warning",
        "Gear 2 Incorrect Ratio",
        "Slipping in second gear, hesitation on 1-2 shift",
        "Check transmission fluid; inspect 2nd gear clutch pack; service or rebuild transmission",
    ),
    (
        "P0733",
        "Transmission",
        "Warning",
        "Gear 3 Incorrect Ratio",
        "Slipping in third gear, poor highway fuel economy",
        "Check transmission fluid; inspect 3rd gear clutch; consider transmission rebuild or replacement",
    ),
    (
        "P0734",
        "Transmission",
        "Warning",
        "Gear 4 Incorrect Ratio",
        "Slipping in 4th gear, poor fuel economy on highway, fault light",
        "Check transmission fluid; inspect 4th gear clutch pack; rebuild or replace transmission",
    ),
    (
        "P0735",
        "Transmission",
        "Warning",
        "Gear 5 Incorrect Ratio",
        "Slipping in 5th gear on 5-speed automatic, fault light",
        "Check transmission fluid; inspect 5th gear clutch; rebuild or replace transmission",
    ),
    (
        "P0741",
        "Transmission",
        "Warning",
        "Torque Converter Clutch Circuit Performance or Stuck Off",
        "Poor fuel economy, RPM flare at highway speed, transmission shudder",
        "Change transmission fluid and filter; replace torque converter; inspect TCC solenoid and wiring",
    ),
    (
        "P0742",
        "Transmission",
        "Warning",
        "Torque Converter Clutch Circuit Stuck On",
        "Engine stalling when coming to a stop, rough idle at stop, fault light",
        "Replace torque converter; inspect and replace TCC solenoid; flush transmission fluid",
    ),
    (
        "P0743",
        "Transmission",
        "Warning",
        "Torque Converter Clutch Circuit Electrical",
        "TCC not engaging, poor highway fuel economy, fault light",
        "Inspect TCC solenoid wiring; replace TCC solenoid; check PCM output for TCC control",
    ),
    (
        "P0745",
        "Transmission",
        "Warning",
        'Pressure Control Solenoid "A" Malfunction',
        "Harsh or slipping shifts, delayed engagement, transmission fault light",
        "Change transmission fluid and filter; replace pressure control solenoid; inspect valve body",
    ),
    (
        "P0751",
        "Transmission",
        "Warning",
        'Shift Solenoid "A" Performance or Stuck Off',
        "Transmission stuck in gear, loss of certain gear ranges, fault light",
        "Change transmission fluid; replace shift solenoid A; inspect valve body for sticking valves",
    ),
    (
        "P0752",
        "Transmission",
        "Warning",
        'Shift Solenoid "A" Stuck On',
        "Transmission unable to shift properly, delayed shifts, fault light",
        "Change transmission fluid; replace shift solenoid A; inspect valve body",
    ),
    (
        "P0755",
        "Transmission",
        "Warning",
        'Shift Solenoid "B" Malfunction',
        "Harsh shifting or no shifting, transmission slipping, fault light",
        "Change transmission fluid and filter; replace shift solenoid B; inspect wiring to solenoid",
    ),
    (
        "P0756",
        "Transmission",
        "Warning",
        'Shift Solenoid "B" Performance or Stuck Off',
        "Loss of certain gear ranges, delayed shifts, fault light",
        "Change fluid; replace shift solenoid B; inspect valve body",
    ),
    (
        "P0760",
        "Transmission",
        "Warning",
        'Shift Solenoid "C" Malfunction',
        "Harsh shifting, transmission stuck in one gear, fault light",
        "Change transmission fluid; replace shift solenoid C; inspect valve body passages",
    ),
    (
        "P0780",
        "Transmission",
        "Warning",
        "Shift Malfunction",
        "Erratic shifting across multiple gears, slipping, fault light",
        "Service transmission fluid and filter; scan for additional codes; inspect shift solenoids and pressure control; rebuild or replace transmission if mechanical failure found",
    ),
    # ── More Vehicle Speed ──────────────────────────────────────────────────────
    (
        "P0501",
        "Throttle",
        "Warning",
        "Vehicle Speed Sensor Range/Performance",
        "Erratic speedometer, ABS warning light, incorrect shift points in automatic",
        "Inspect VSS wiring and connector; replace vehicle speed sensor; check tone ring on output shaft",
    ),
    (
        "P0502",
        "Throttle",
        "Warning",
        "Vehicle Speed Sensor Low Input",
        "Speedometer reads zero, no cruise control, transmission shift issues",
        "Inspect VSS wiring for short to ground; replace vehicle speed sensor",
    ),
    (
        "P0503",
        "Throttle",
        "Warning",
        "Vehicle Speed Sensor Intermittent/Erratic/High",
        "Speedometer fluctuates, intermittent cruise control dropout, erratic ABS",
        "Inspect VSS connector for corrosion; check tone ring for damage; replace vehicle speed sensor",
    ),
    # ── More Throttle (Pedal Position Sensor B) ─────────────────────────────────
    (
        "P0220",
        "Throttle",
        "Warning",
        "Throttle/Pedal Position Sensor/Switch B Circuit Malfunction",
        "Reduced engine power warning, limp mode, stalling",
        "Inspect TPS B wiring and connector; clean throttle body; replace throttle body or pedal position sensor assembly",
    ),
    (
        "P0221",
        "Throttle",
        "Warning",
        "Throttle/Pedal Position Sensor/Switch B Circuit Range/Performance",
        "Reduced power, hesitation, check engine light",
        "Inspect throttle body for carbon buildup; clean with throttle cleaner; replace throttle body if TPS B reading is erratic",
    ),
    (
        "P0222",
        "Throttle",
        "Warning",
        "Throttle/Pedal Position Sensor/Switch B Circuit Low Input",
        "Limp mode, reduced power, check engine light",
        "Check TPS B wiring for short to ground; replace throttle body or APP sensor; perform throttle body relearn",
    ),
    (
        "P0223",
        "Throttle",
        "Warning",
        "Throttle/Pedal Position Sensor/Switch B Circuit High Input",
        "Limp mode, engine surging, check engine light",
        "Check TPS B wiring for open circuit or short to voltage; replace throttle body; perform idle relearn",
    ),
    (
        "P0506",
        "Throttle",
        "Warning",
        "Idle Control System RPM Lower Than Expected",
        "Engine stalls at idle, very low RPM at idle, rough idle",
        "Clean throttle body and IAC valve passages; replace IAC valve; check for vacuum leaks lowering idle",
    ),
    # ── Network / Communication ─────────────────────────────────────────────────
    (
        "U0073",
        "Network & Communication",
        "Critical",
        "Control Module Communication Bus Off",
        "Multiple system faults simultaneously, check engine light, various warning lights",
        "Inspect CAN bus wiring for shorts or open circuits; check all module connectors; verify battery voltage and ground integrity",
    ),
    (
        "U0100",
        "Network & Communication",
        "Critical",
        'Lost Communication With ECM/PCM "A"',
        "Multiple warning lights, transmission or ABS faults caused by loss of engine data",
        "Check PCM power supply fuses and grounds; inspect CAN bus wiring to PCM; replace PCM if power and bus are confirmed good",
    ),
    (
        "U0101",
        "Network & Communication",
        "Warning",
        "Lost Communication With Transmission Control Module (TCM)",
        "Transmission may default to limp mode, no adaptive shifting, fault light",
        "Check TCM power and grounds; inspect CAN bus wiring to TCM; replace TCM if communication cannot be restored",
    ),
    (
        "U0121",
        "Network & Communication",
        "Critical",
        "Lost Communication With Anti-Lock Brake System (ABS) Control Module",
        "ABS and stability control warning lights, ABS and TCS may be disabled",
        "Check ABS module power and grounds; inspect CAN bus wiring; replace ABS module if confirmed faulty",
    ),
    (
        "U0131",
        "Network & Communication",
        "Warning",
        "Lost Communication With Power Steering Control Module",
        "Power steering warning light, heavy steering (EPS disabled)",
        "Check EPS module power supply; inspect CAN bus wiring; replace EPS module if communication fault persists",
    ),
    (
        "U0140",
        "Network & Communication",
        "Warning",
        "Lost Communication With Body Control Module (BCM)",
        "Multiple body function failures: windows, lights, door locks not responding, warning lights",
        "Check BCM fuses and grounds; inspect CAN bus and LIN bus wiring; replace BCM if confirmed faulty",
    ),
    (
        "U0155",
        "Network & Communication",
        "Info",
        "Lost Communication With Instrument Panel Cluster (IPC)",
        "Instrument cluster not working, gauges inoperative, warning lights out",
        "Check IPC fuse and power supply; inspect CAN bus wiring to IPC; replace instrument cluster if confirmed faulty",
    ),
    (
        "U0164",
        "Network & Communication",
        "Info",
        "Lost Communication With HVAC Control Module",
        "Climate control not responding, fan or temperature settings ignored, HVAC fault",
        "Check HVAC module fuses; inspect CAN/LIN bus wiring; replace HVAC control module if fault persists",
    ),
    (
        "U0184",
        "Network & Communication",
        "Info",
        "Lost Communication With Radio",
        "Radio inoperative, audio system fault, may affect steering wheel controls",
        "Check radio fuse and power supply; inspect CAN bus connection to radio; replace radio head unit if confirmed faulty",
    ),
    (
        "U0401",
        "Network & Communication",
        "Warning",
        'Invalid Data Received From ECM/PCM "A"',
        "Transmission or ABS acting on incorrect engine data, multiple warning lights",
        "Check PCM for internal faults and update software; inspect CAN bus wiring for intermittent faults; replace PCM if sending corrupt data",
    ),
    (
        "U0402",
        "Network & Communication",
        "Warning",
        "Invalid Data Received From Transmission Control Module (TCM)",
        "Incorrect gear information to engine, rough or erratic shifting behavior reported to other modules",
        "Check TCM software version and update if available; inspect CAN bus; replace TCM if sending invalid data",
    ),
]


def seed(db_path: Path) -> None:
    with sqlite3.connect(db_path) as conn:
        # Apply schema statements one by one
        for statement in SCHEMA.strip().split(";"):
            stmt = statement.strip()
            if stmt:
                conn.execute(stmt)
        # Triggers contain semicolons inside BEGIN...END so use executescript
        conn.executescript(FTS_TRIGGERS)
        conn.executemany(
            "INSERT OR REPLACE INTO dtc_codes (code, category, severity, description, symptoms, fix) VALUES (?, ?, ?, ?, ?, ?)",
            DTC_DATA,
        )
        # Rebuild FTS to sync all rows (triggers fire per row already, but rebuild is a safety net)
        conn.execute("INSERT INTO dtc_codes_fts(dtc_codes_fts) VALUES ('rebuild')")
        conn.commit()
    print(f"Seeded {len(DTC_DATA)} DTC codes into {db_path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Seed the OBD-II SQLite database.")
    parser.add_argument(
        "--db",
        type=Path,
        default=DEFAULT_DB_PATH,
        help="Path to the SQLite database file (default: ./obd2.db)",
    )
    args = parser.parse_args()
    seed(args.db)
